language: python
python: 3.5
env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=pypy3
install: pip install -U tox
script: tox
deploy:
  provider: pypi
  user: Apptimize
  password:
    secure: Eod45gX7hEA8NzVoE6KT4HWaQtGzJzWoi1k5ZLYfmANyEobq75Qldy+feoZAstaB448WfiP/ii5JF35Lo2YRjN6CePNnOavElTOw7f3WaqBhYfUmn0EJ6+n2y900oj3FQl8SVam8noyU8DFqQcXysDsor+1MBO4pGK/PtGOCUOvzn4iwKKrV5Bq/kdCxQKqXx3dBaO+crVzA6F2lvWCdeAb5VJJlO/rZOYoT6fLlUNrD7+y0Wi317zEXbqwIvBrKlkEghYk/fWvugSk0z3XudRH33w6VedxuOPvmlbuHS09u8E/d9WS9y4QdzF0umHcWPiyMdigV4FJW8xbRsqhzFDYaSL/p6vljDaJoa6Fc+CXJUBITFsjlJFqRHpjZvX9IE1nVlwnEfYOTrdQCLCtO7G9vFSdjuInTxw6Z+UEmwJ8EvrTZpqHwdlZWVpuPVD/XL/95LtZmhFCYiTn5t7EnVyoUEGmgxqYypQMG4qYjfgEU25LdjRykFCe6UU3AF4zibljf8FMspth+skp2ZUAw9/Rf3umLkqbwSkqYVeouAeVdt2tHiGmowOa+DGzoVKz40PFwoT1iYF6YyOtk+ExiYrCj3Vy7adZPMTKK39K5I1caF6g//H3fcbvqqR485tiDSdNKc3O9I5FEnb39F/J0T/bNr7kL9iDzw63foB+fAqY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Apptimize-OSS/github-reviewboard-sync
